# Homework 2
Calculating Distances in water molecule

In [1]:
import os,numpy

In [64]:
mol_file = os.path.join('data','water.xyz')
print(mol_file)

data\water.xyz


In [10]:
data = numpy.genfromtxt(fname=mol_file,delimiter='',dtype='unicode',skip_header=2)

In [11]:
num_atoms=len(data)

In [20]:
label = data[:,0] #all rows, first col
coords = data[:,1:4].astype(float) #get float array of coords

In [25]:
for i in range(0,num_atoms):
    for j in range(0,i):
        dist_val = numpy.sqrt( (coords[i][0]-coords[j][0])**2 + (coords[i][1]-coords[j][1])**2 + (coords[i][2]-coords[j][2])**2 )
        if dist_val < 1.5: #arbitrary cutoff so that atoms not truly "bonded" aren't printed
            print(F'{label[i]}-{label[j]:4} : {dist_val:.3f}')

H1-O    : 0.969
H2-O    : 0.969


## Writing and Using Functions

In [26]:
#def function_name(parameters):
#    body of the function
#    write code using paramaters to calcualte something
#    return some_value

In [30]:
def dist(coords1,coords2): #when designing functions, aim for simple inputs and simple outputs
    value = numpy.sqrt( (coords1[0]-coords2[0])**2 + (coords1[1]-coords2[1])**2 + (coords1[2]-coords2[2])**2 )
    return value

In [31]:
dist([0,0,0],[0,0,1])

1.0

In [32]:
for i in range(0,num_atoms):
    for j in range(0,i):
        dist_val = dist(coords[i],coords[j])
        if dist_val < 1.5: #arbitrary cutoff so that atoms not truly "bonded" aren't printed
            print(F'{label[i]}-{label[j]:4} : {dist_val:.3f}')

H1-O    : 0.969
H2-O    : 0.969


In [39]:
#creat function for checking bond length
def bond_check(atom_distance):
    if atom_distance <= 1.5:
        return True
    else:
        return False

In [42]:
#using new function
bond_check(1.7)

False

In [43]:
#modify bond check function to take min and max length as input
def bond_check(mind,maxd,atom_distance):
    if atom_distance <= maxd and atom_distance > mind:
        return True
    else:
        return False

In [45]:
bond_check(0.0,1.7,1.7)

True

In [58]:
#modify bond check to create default min and max if not provided by user

def bond_check(atom_distance,mind=0.0,maxd=1.5): #variables with default values MUST come after those with no defaul  ts
    """
    This function checks if a distance is a bond based on a minimum and maximum.
    Inputs: distance, minimum length, maximum length
    Defaults: minimum: 0.0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance <= maxd and atom_distance > mind:
        return True
    else:
        return False

In [49]:
bond_check(1.7)

False

In [52]:
bond_check(1.7,mind=0.0)

False

In [53]:
bond_check(1.7,maxd=2.0) #note variables with default values being changes don't have to be listed in order

True

In [59]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(atom_distance, mind=0.0, maxd=1.5)
    This function checks if a distance is a bond based on a minimum and maximum.
    Inputs: distance, minimum length, maximum length
    Defaults: minimum: 0.0 angstroms, maximum: 1.5 angstroms



In [63]:
#modifying code again
for i in range(0,num_atoms):
    for j in range(0,i):
        dist_val = dist(coords[i],coords[j])
        if bond_check(dist_val) is True: 
            print(F'{label[i]}-{label[j]:4} : {dist_val:.3f}')

H1-O    : 0.969
H2-O    : 0.969


In [71]:
#create function for opening and processing xyz file. Have function accept filepath for input
def open_xyz(file_path):
    """
    Opens a standard xyz file.
    Returns the symbols as a 1D array of strings and the coords as a 2D array of floats.
    """
    all_data = numpy.genfromtxt(fname=file_path,dtype='unicode',skip_header=2) #don't need delimiter, because breaking on blank space is the default
    atom_label = all_data[:,0] #all rows, first col
    atom_coords = all_data[:,1:4].astype(float) #get float array of coords
    return atom_label,atom_coords

In [70]:
mol_file = os.path.join('data','water.xyz')
label,coords = open_xyz(mol_file)
print(label)
print()
print(coords)

['O' 'H1' 'H2']

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [72]:
help(open_xyz)

Help on function open_xyz in module __main__:

open_xyz(file_path)
    Opens a standard xyz file.
    Returns the symbols as a 1D array of strings and the coords as a 2D array of floats.



In [74]:
import os,numpy

def dist(coords1,coords2): #when designing functions, aim for simple inputs and simple outputs
    value = numpy.sqrt( (coords1[0]-coords2[0])**2 + (coords1[1]-coords2[1])**2 + (coords1[2]-coords2[2])**2 )
    return value

def bond_check(atom_distance,mind=0.0,maxd=1.5): #variables with default values MUST come after those with no defaults
    """
    This function checks if a distance is a bond based on a minimum and maximum.
    Inputs: distance, minimum length, maximum length
    Defaults: minimum: 0.0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance <= maxd and atom_distance > mind:
        return True
    else:
        return False
    
def open_xyz(file_path):
    """
    Opens a standard xyz file.
    Returns the symbols as a 1D array of strings and the coords as a 2D array of floats.
    """
    all_data = numpy.genfromtxt(fname=file_path,dtype='unicode',skip_header=2) #don't need delimiter, because breaking on blank space is the default
    atom_label = all_data[:,0] #all rows, first col
    atom_coords = all_data[:,1:4].astype(float) #get float array of coords
    return atom_label,atom_coords

file_location = os.path.join('data','water.xyz')
label,coords = open_xyz(file_location)

num_atoms = len(label)

for i in range(0,num_atoms):
    for j in range(0,i):
        dist_val = dist(coords[i],coords[j])
        if bond_check(dist_val) is True: 
            print(F'{label[j]}-{label[i]:4} : {dist_val:.3f}')

O-H1   : 0.969
O-H2   : 0.969
